In [1]:
import numpy as np
n1 = np.random.randint(1,100,size=(5,5))
n1

array([[67, 88, 75, 42, 97],
       [40, 49, 99, 39, 12],
       [78, 78, 12, 75, 11],
       [81, 57, 68, 63, 57],
       [75, 74, 37, 21, 73]])

In [2]:
n2=np.random.rand(3,4)
n2

array([[0.09596249, 0.92757713, 0.14668622, 0.63472225],
       [0.62963817, 0.91343622, 0.35734858, 0.76449462],
       [0.76330857, 0.43587245, 0.12981229, 0.10743097]])

In [3]:
print(n2)

[[0.09596249 0.92757713 0.14668622 0.63472225]
 [0.62963817 0.91343622 0.35734858 0.76449462]
 [0.76330857 0.43587245 0.12981229 0.10743097]]


Pandas

In [4]:
import pandas as pd
df=pd.DataFrame(n1)

In [6]:
import pandas as pd
df2=pd.DataFrame(n2)

In [7]:
df

0   1   2   3   4
0  67  88  75  42  97
1  40  49  99  39  12
2  78  78  12  75  11
3  81  57  68  63  57
4  75  74  37  21  73

In [8]:
#df.describe()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       5 non-null      int32
 1   1       5 non-null      int32
 2   2       5 non-null      int32
 3   3       5 non-null      int32
 4   4       5 non-null      int32
dtypes: int32(5)
memory usage: 228.0 bytes


In [9]:
n2=np.random.rand(5,6)
df3 =pd.DataFrame(n2)
df3

0         1         2         3         4         5
0  0.458440  0.488642  0.033369  0.506152  0.140345  0.854750
1  0.320885  0.692227  0.989757  0.900686  0.759455  0.926627
2  0.927743  0.627543  0.175831  0.427815  0.196376  0.521809
3  0.336989  0.306883  0.737300  0.781137  0.602294  0.645718
4  0.627798  0.647956  0.432977  0.508654  0.849043  0.451152

In [10]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       5 non-null      float64
 1   1       5 non-null      float64
 2   2       5 non-null      float64
 3   3       5 non-null      float64
 4   4       5 non-null      float64
 5   5       5 non-null      float64
dtypes: float64(6)
memory usage: 368.0 bytes


In [11]:
df3.describe()

0         1         2         3         4         5
count  5.000000  5.000000  5.000000  5.000000  5.000000  5.000000
mean   0.534371  0.552650  0.473847  0.624889  0.509503  0.680011
std    0.251879  0.157061  0.393724  0.204282  0.324307  0.206115
min    0.320885  0.306883  0.033369  0.427815  0.140345  0.451152
25%    0.336989  0.488642  0.175831  0.506152  0.196376  0.521809
50%    0.458440  0.627543  0.432977  0.508654  0.602294  0.645718
75%    0.627798  0.647956  0.737300  0.781137  0.759455  0.854750
max    0.927743  0.692227  0.989757  0.900686  0.849043  0.926627

In [13]:
df3.shape

(5, 6)

In [14]:
df3.size

30

In [19]:
df3.head(7)

0         1         2         3         4         5
0  0.458440  0.488642  0.033369  0.506152  0.140345  0.854750
1  0.320885  0.692227  0.989757  0.900686  0.759455  0.926627
2  0.927743  0.627543  0.175831  0.427815  0.196376  0.521809
3  0.336989  0.306883  0.737300  0.781137  0.602294  0.645718
4  0.627798  0.647956  0.432977  0.508654  0.849043  0.451152

In [20]:
df3.tail(5)

0         1         2         3         4         5
0  0.458440  0.488642  0.033369  0.506152  0.140345  0.854750
1  0.320885  0.692227  0.989757  0.900686  0.759455  0.926627
2  0.927743  0.627543  0.175831  0.427815  0.196376  0.521809
3  0.336989  0.306883  0.737300  0.781137  0.602294  0.645718
4  0.627798  0.647956  0.432977  0.508654  0.849043  0.451152